### ISSUE TITLE
Searching with txt output doesn't find some things that html output does

### ISSUE THREAD

**Issue by rowanthorpe** [servermon/servermon#89]
I'm almost sure this isn't install-specific for us. When I search (either in a browser or from the commandline with curl/wget) this:

```
 https://servermon.domain.com/search?q=a.fqdn.com
```

I get the expected output, but when I search with text output:

```
 https//servermon.domain.com/search?txt&q=a.fqdn.com
```

It fails to find it. Search with "txt" works when searching by e.g. ipmi hostname, etc. As far as I've found it seems to only not find results when searching by FQDN or hostname in txt mode...

**Comment by akosiaris** [comment]
Yes, that is expected. See:

https://github.com/servermon/servermon/blob/master/servermon/projectwide/templates/results.txt

The reasoning behind this is that the "TXT" (as well as the CSV) versions are a poor man's (a really poor man's) API to hwdoc. Meant to be easily curl | awk or grep to get some data quickly. So the puppet or the updates apps have no code stanzas for them.

All in all, the idea is to get a decent REST API at some point and deprecate these 2 views as they are there more as a convenience rather than a good solution

**Comment by rowanthorpe** [comment]
OK, thanks for the executive summary. Feel free to close this. Quick question though: because a full-blown REST API is probably not just around the corner yet, are you open to any small incremental improvements to this interface in the meantime? or do you want to discourage any efforts at all with that? (my motivations are entirely selfish, driven by present usage-needs).

**Comment by akosiaris** [comment]
OK, thanks. Closing. Yes I am open to any improvements you got to offer to that thing. My only guideline would be "try to keep it easily parseable". That is, don't go for a format that needs a state machine to be parsed such as header lines, sections etc. Try to stay along the one line per result path.
